[package]

name = "geojson"
description = "Library for serializing the GeoJSON vector GIS file format"
version = "0.7.0"
authors = ["Corey Farwell <coreyf@rwell.org>",
           "Blake Grotewold <hello@grotewold.me>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/rust-geojson"
readme = "README.md"
documentation = "https://georust.github.io/rust-geojson/"
keywords = ["geojson", "gis", "json", "geo"]

[dependencies]
serde = "~1.0"
serde_json = "~1.0"
geo = "^0.4"
num-traits = "0.1"
