[package]

name = "geojson"
description = "GeoJSON utilities for Rust"
version = "0.0.9"
authors = ["Corey Farwell <coreyf@rwell.org>",
           "Blake Grotewold <hello@grotewold.me>"]
license = "Apache-2.0"
repository = "https://github.com/georust/rust-geojson"
readme = "README.md"

[dependencies]
rustc-serialize = "0.3"
