[package]

name = "geojson"
description = "Library for serializing the GeoJSON vector GIS file format"
version = "0.4.1"
authors = ["Corey Farwell <coreyf@rwell.org>",
           "Blake Grotewold <hello@grotewold.me>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/rust-geojson"
readme = "README.md"
documentation = "https://georust.github.io/rust-geojson/"
keywords = ["geojson", "gis", "json", "geo"]

[features]
default = ["rustc-serialize", "geo-interop"]
with-serde = ["serde","serde_json"]
geo-interop = ["geo", "num"]

[dependencies]
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "~0.8", optional = true }
serde_json = { version = "~0.8", optional = true }
geo = { version = "^0.3", optional = true }
num = { version = "0.1", optional = true }
