[package]

name = "geojson"
description = "GeoJSON utilities for Rust"
version = "0.0.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "Apache-2.0"
repository = "https://github.com/frewsxcv/rust-geojson"
