[package]

name = "geojson"
description = "Library for serializing the GeoJSON vector GIS file format"
version = "0.2.0"
authors = ["Corey Farwell <coreyf@rwell.org>",
           "Blake Grotewold <hello@grotewold.me>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/rust-geojson"
readme = "README.md"
documentation = "https://georust.github.io/rust-geojson/"
keywords = ["geojson", "gis", "json", "geo"]

[features]
default = ["rustc-serialize"]
with-serde = ["serde","serde_json"]

[dependencies]
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "~0.7", optional = true }
serde_json = { version = "~0.7", optional = true }